# Generated by Django 3.0.8 on 2020-09-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200928_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='user_id',
            new_name='user',
        ),
    ]
