# Generated by Django 3.0.8 on 2020-11-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201028_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='keys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
